# Makefile for hw2_chat_server

CC = g++
CFLAGS = -std=c++11
SRC = hw2_chat_server.cpp
OUT = hw2_chat_server

all: $(OUT)

$(OUT): $(SRC)
	$(CC) $(CFLAGS) -o $(OUT) $(SRC)
	//./$(OUT)

clean:
	rm -f $(OUT)
